extends Resource
class_name Neo4jChangeDataCapturePayload

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# Neo4jChangeDataCapturePayload Model


# Required: True
# isArray: false
@export var after: Dictionary:
	set(value):
		__after__was__set = true
		after = value
var __after__was__set := false

# Required: True
# isArray: false
@export var before: String = "":
	set(value):
		__before__was__set = true
		before = value
var __before__was__set := false

# Required: True
# isArray: false
@export var id: String = "":
	set(value):
		__id__was__set = true
		id = value
var __id__was__set := false

# Required: True
# isArray: false
@export var type: String = "":
	set(value):
		__type__was__set = true
		type = value
var __type__was__set := false

# Required: True
# isArray: false
@export var end: Neo4jChangeDataCaptureRelationshipPayloadEnd:
	set(value):
		__end__was__set = true
		end = value
var __end__was__set := false

# Required: True
# isArray: false
@export var label: String = "":
	set(value):
		__label__was__set = true
		label = value
var __label__was__set := false

# Required: True
# isArray: false
@export var start: Neo4jChangeDataCaptureRelationshipPayloadEnd:
	set(value):
		__start__was__set = true
		start = value
var __start__was__set := false


func bzz_collect_missing_properties() -> Array:
	var bzz_missing_properties := Array()
	if not self.__after__was__set:
		bzz_missing_properties.append("after")
	if not self.__before__was__set:
		bzz_missing_properties.append("before")
	if not self.__id__was__set:
		bzz_missing_properties.append("id")
	if not self.__type__was__set:
		bzz_missing_properties.append("type")
	if not self.__end__was__set:
		bzz_missing_properties.append("end")
	if not self.__label__was__set:
		bzz_missing_properties.append("label")
	if not self.__start__was__set:
		bzz_missing_properties.append("start")
	return bzz_missing_properties


func bzz_normalize() -> Dictionary:
	var bzz_dictionary := Dictionary()
	if self.__after__was__set:
		bzz_dictionary["after"] = self.after
	if self.__before__was__set:
		bzz_dictionary["before"] = self.before
	if self.__id__was__set:
		bzz_dictionary["id"] = self.id
	if self.__type__was__set:
		bzz_dictionary["type"] = self.type
	if self.__end__was__set:
		bzz_dictionary["end"] = self.end
	if self.__label__was__set:
		bzz_dictionary["label"] = self.label
	if self.__start__was__set:
		bzz_dictionary["start"] = self.start
	return bzz_dictionary


# Won't work for JSON+LD
static func bzz_denormalize_single(from_dict: Dictionary):
	var me := new()
	if from_dict.has("after"):
		me.after = from_dict["after"]
	if from_dict.has("before"):
		me.before = from_dict["before"]
	if from_dict.has("id"):
		me.id = from_dict["id"]
	if from_dict.has("type"):
		me.type = from_dict["type"]
	if from_dict.has("end"):
		me.end = Neo4jChangeDataCaptureRelationshipPayload_end.bzz_denormalize_single(from_dict["end"])
	if from_dict.has("label"):
		me.label = from_dict["label"]
	if from_dict.has("start"):
		me.start = Neo4jChangeDataCaptureRelationshipPayload_end.bzz_denormalize_single(from_dict["start"])
	return me


# Won't work for JSON+LD
static func bzz_denormalize_multiple(from_array: Array):
	var mes := Array()
	for element in from_array:
		if element is Array:
			mes.append(bzz_denormalize_multiple(element))
		elif element is Dictionary:
			# TODO: perhaps check first if it looks like a match or an intermediate container
			mes.append(bzz_denormalize_single(element))
		else:
			mes.append(element)
	return mes

