extends Resource
class_name Neo4jChangeDataCaptureRelationshipPayloadEnd

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# Neo4jChangeDataCaptureRelationshipPayloadEnd Model


# Required: True
# isArray: false
@export var id: String = "":
	set(value):
		__id__was__set = true
		id = value
var __id__was__set := false

# Required: True
# isArray: false
@export var ids: Dictionary:
	set(value):
		__ids__was__set = true
		ids = value
var __ids__was__set := false

# Required: True
# isArray: true
@export var labels: Array:
	set(value):
		__labels__was__set = true
		labels = value
var __labels__was__set := false


func bzz_collect_missing_properties() -> Array:
	var bzz_missing_properties := Array()
	if not self.__id__was__set:
		bzz_missing_properties.append("id")
	if not self.__ids__was__set:
		bzz_missing_properties.append("ids")
	if not self.__labels__was__set:
		bzz_missing_properties.append("labels")
	return bzz_missing_properties


func bzz_normalize() -> Dictionary:
	var bzz_dictionary := Dictionary()
	if self.__id__was__set:
		bzz_dictionary["id"] = self.id
	if self.__ids__was__set:
		bzz_dictionary["ids"] = self.ids
	if self.__labels__was__set:
		bzz_dictionary["labels"] = self.labels
	return bzz_dictionary


# Won't work for JSON+LD
static func bzz_denormalize_single(from_dict: Dictionary):
	var me := new()
	if from_dict.has("id"):
		me.id = from_dict["id"]
	if from_dict.has("ids"):
		me.ids = from_dict["ids"]
	if from_dict.has("labels"):
		me.labels = from_dict["labels"]
	return me


# Won't work for JSON+LD
static func bzz_denormalize_multiple(from_array: Array):
	var mes := Array()
	for element in from_array:
		if element is Array:
			mes.append(bzz_denormalize_multiple(element))
		elif element is Dictionary:
			# TODO: perhaps check first if it looks like a match or an intermediate container
			mes.append(bzz_denormalize_single(element))
		else:
			mes.append(element)
	return mes

